spring:
  profiles: 
    active: local
   
# local    
---
spring:
  profiles: local
server:
  port: 8081
hyperledger:
  fabric:
    orderers:
      - name: orderer.example.com
        location: grpcs://192.168.56.1:7050
    peers:
      - name: peer0.org1.example.com
        location: grpcs://192.168.56.1:7051
  #    - name: peer1.org1.example.com 
  #      location: grpcs://192.168.56.1:8051  
    msp: Org1MSP
    affiliation: org1
    userName: admin
    channel: mychannel
  
# dev  
---
spring:
  profiles: dev
server:
  port: 8081      
